# Shows a "Sponsor" button at the top of the repo.
# https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
ko_fi: chanuwatsrithong
